### ISSUE TITLE
Passage listing broken from v.0.27.0

### ISSUE THREAD

**Issue by ChristopherMerriner** [cyrusfirheir/twee3-language-tools#163]
Passage listing is disabled ("passage listing is turned off") and the 'enable' button doesn't work to bring it back. Seems to be a problem from v.0.27.0 upwards. Reverting to v.0.26.1 brings the passage listing back.

**Comment by cyrusfirheir** [comment]
Yeah a few people have been experiencing the issue. It's still not clear what the cause is, and I cannot reproduce it on my machine either.

For now, a workaround is to move the contents of the project to a different directory and launch a new workspace from that directory. Any existing workspace from before v0.27.0 seems to be affected for the people who have the issue.
