### ISSUE TITLE
Installed, but not working

### ISSUE THREAD

**Issue by BadGriffin** [cyrusfirheir/twee3-language-tools#24]
I'm not sure where else to put this, but I am not seeing syntax highlighting when I am trying to use this extension. VSC shows it's installed but passage listing is turned off and I can't enable it, and the buttons in the passage listing side pane pop errors "Command 'twee3LanguageTools.passage.list' not found" and "Command 'twee3LanguageTools.storyMap.show' not found"

**Comment by cyrusfirheir** [comment]
I'd be able to help better in the Twine Games Discord server, but the usual issues are:
1. Opening a single file instead of a folder/workspace,
2. Not having a `StoryData` passage with valid storyformat and version explicitly mentioned.

The README lists the [basic requirements](https://github.com/cyrusfirheir/twee3-language-tools#requirements), check for those first. Should resolve the issue.

And on that note, I think I should move the requirements to the top of the README so people don't miss it.

**Comment by cyrusfirheir** [comment]
@BadGriffin hopefully you solved the problem. Since there haven't been any follow ups, I am assuming you've resolved the issue, whatever it was. Closing.
