### ISSUE TITLE
Extension incorrectly reports unclosed macros in script

### ISSUE THREAD

**Issue by hogart** [cyrusfirheir/twee3-language-tools#3]
I have [a macro](https://github.com/hogart/sugar-cube-utils/blob/master/dlg.js) which throws errors when used incorrectly (like this: `this.error('missing <<dlg>> <<level>> number');`, [see line 76](https://github.com/hogart/sugar-cube-utils/blob/master/dlg.js#L76)).
The inspection reports `Malformed container macro! Closing 'dlg' tag not found!` when the macro code is in the story's script.

**Comment by cyrusfirheir** [comment]
Thanks for the alert! Fixed.

Because `.js` and `.css` files are used more often than `script` and `stylesheet` tagged passages, that had totally gone under the radar. The extension already makes exceptions for `<script>` and `<style>` HTML tags (and the `<<script>>` SC macro, at that) but hadn't thought about the entire passage being JS or CSS.
