### ISSUE TITLE
The extension could benefit from providing file icons for *.twee and *.tw files 

### ISSUE THREAD

**Issue by hogart** [cyrusfirheir/twee3-language-tools#5]
I wouldn't mind setting it up manually, but there seems to be no such setting in VS Code. 
Twine icon instead of default "plain text" would improve navigation in big projects.

From the quick look at [docs](https://code.visualstudio.com/api/extension-guides/file-icon-theme) it doesn't seem to difficult to implement.

**Comment by cyrusfirheir** [comment]
I'd love to add icons, but the issue is you can't extend icon themes as of now. If I were to define a new theme with just icons for Twee files, everything else would go blank. There are a few issues open on the VSC repo, let's see what happens.

There's an icon theme that does have icons for Twee files: [file-icons](https://marketplace.visualstudio.com/items?itemName=file-icons.file-icons). Maybe I should add that to extension recommendations? I personally don't use it, but could be useful.

Other than that, [vscode-icons](https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons) (which I do use) is the only file icon extension with customisation in mind. I haven't tinkered with it yet, but it should be [possible](https://github.com/vscode-icons/vscode-icons/wiki/Customization) to add new icons. And if it can't be automated, I'll at least write a little guide as to how to go about it.

**Comment by hogart** [comment]
My bad, I didn't knew that it's not possible to extend current file icons. I'll take a look at files-icons, thanks!

**Comment by caberg** [comment]
Or you can use @[Vscode-material-icon-theme](https://github.com/PKief/vscode-material-icon-theme) extension
refer to this @[Issue](https://github.com/PKief/vscode-material-icon-theme/issues/874)  for manual setting for now
Just wait for my pull request approved to automatically implemented for twee3 language
