### ISSUE TITLE
Bug: There is no error/warning if you use two <<else>>'s in the same <<if>> statement

### ISSUE THREAD

**Issue by AcademyOfF** [cyrusfirheir/twee3-language-tools#85]
It's nice how the if statement goes red if you are missing a closing tag. I just noticed this doesn't happen if you use more than one `<<else>>`' in the same `<<if>>` statement. If you render such an if statement at runtime, it gives this error:
```
Error: <<if>>: <<else>> must be the final clause
```
It would be nice if the first `else` had a red underline with a tooltip with the same message.

Example code with the problem:

```
          <<if conditional>>
            ...
          <<else>>
          <<else>>
            ...
          <</if>>
```

**Comment by cyrusfirheir** [comment]
Child macros and their position and stuff aren't validated as of now. Currently, the parser only sees the entire `if` block, and not different sections inside it.

**Comment by MinusGix** [comment]
We might be able to do this:  
- Get the range for the `if` macro we're looking at
- Create an array
- Iterate over all macros (starting after current). Filter so that their start is within the `if` macros range.
- For each of those macros, if they're a container macro then we filter out all the macros within its range, this avoids checking the macros inside the container which would be bad
- If it is one of our `children` macros then we keep a count of it (probably only for ones with `max` field defined on them, where we need to do that)
- If it goes over the `max` field (we could also easily add a `min`, but I'm unsure if there's any which would benefit from that?) then we warn.
It is a bit more expensive to compute than I'd like, but avoids generating an entire tree since we don't need it. I'll try implementing this.  
It would allow for a `min` requirement, as well as requirements like `else` must always be after either nothing (`if`) or `elseif` (though this one is a bit more complex).
